replicaCount: 2

image:
  repository: legiahoangthien/library-notification-service
  tag: "prod-initial"

service:
  type: ClusterIP
  port: 4004

needsDatabase: true

env:
  NODE_ENV: "production"
  PORT: "4004"
