replicaCount: 1

image:
  repository: legiahoangthien/library-notification-service
  tag: "dev-b04ab8a7eda2a476518a78e54190d29d67ace976"

service:
  type: ClusterIP
  port: 4004

# Flag to determine if this service needs MongoDB credentials from Secret
needsDatabase: true

env:
  NODE_ENV: "development"
  PORT: "4004"
