replicaCount: 2

image:
  repository: legiahoangthien/library-frontend
  tag: "prod-b8624f8e03a8b06f66dd20e6f3c24107a0b1e919"

service:
  type: ClusterIP
  port: 3000

needsDatabase: false

env:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://api.thuvien.vn"
