replicaCount: 1

image:
  repository: legiahoangthien/library-frontend
  tag: "dev-4355e1ee805c7a024eb580b8e74ed54608bee300"

service:
  type: ClusterIP
  port: 3000

# Flag to determine if this service needs MongoDB credentials from Secret
needsDatabase: false

env:
  NODE_ENV: "development"
  NEXT_PUBLIC_API_URL: "http://gateway-svc:80"
