replicaCount: 2

image:
  repository: legiahoangthien/library-frontend
  tag: "prod-d0d1944083c2529becbd5b7a64ad3c932a37d801"

service:
  type: ClusterIP
  port: 3000

needsDatabase: false

env:
  NODE_ENV: "development"
  NEXT_PUBLIC_API_URL: "http://gateway-svc:80"
  HOSTNAME: "0.0.0.0"    # <-- Ép Next.js mở cửa cho mọi kết nối
  PORT: "3000"