replicaCount: 2

image:
  repository: legiahoangthien/library-frontend
  tag: "prod-524f0bc908c17bd2aa2b0f7acaa6a9a98cc6961e"

service:
  type: ClusterIP
  port: 3000

needsDatabase: false

env:
  NODE_ENV: "development"
  NEXT_PUBLIC_API_URL: "http://192.168.127.7:4000"
  HOSTNAME: "0.0.0.0"    # <-- Ép Next.js mở cửa cho mọi kết nối
  PORT: "3000"