replicaCount: 1

image:
  repository: lghthien/library-gateway
  tag: "dev-97df315ea31b5950ee394e10b7d3bc694d2294ef"

service:
  type: ClusterIP
  port: 4000

# Flag to determine if this service needs MongoDB credentials from Secret
needsDatabase: false

env:
  NODE_ENV: "development"
  PORT: "4000"
