replicaCount: 1

image:
  repository: legiahoangthien/library-parameter-service
  tag: "dev-4355e1ee805c7a024eb580b8e74ed54608bee300"

service:
  type: ClusterIP
  port: 4007

# Flag to determine if this service needs MongoDB credentials from Secret
needsDatabase: true

env:
  NODE_ENV: "development"
  PORT: "4007"
