replicaCount: 2

image:
  repository: legiahoangthien/library-parameter-service
  tag: "prod-524f0bc908c17bd2aa2b0f7acaa6a9a98cc6961e"

service:
  type: ClusterIP
  port: 4007

needsDatabase: true

env:
  NODE_ENV: "production"
  PORT: "4007"
