replicaCount: 1

image:
  repository: legiahoangthien/library-catalog-service
  tag: "dev-initial"

service:
  type: ClusterIP
  port: 4002

# Flag to determine if this service needs MongoDB credentials from Secret
needsDatabase: true

env:
  NODE_ENV: "development"
  PORT: "4002"
