replicaCount: 2

image:
  repository: legiahoangthien/library-catalog-service
  tag: "prod-initial"

service:
  type: ClusterIP
  port: 4002

needsDatabase: true

env:
  NODE_ENV: "production"
  PORT: "4002"
