replicaCount: 1

image:
  repository: lghthien/library-report-service
  tag: "dev-initial"

service:
  type: ClusterIP
  port: 4003

# Flag to determine if this service needs MongoDB credentials from Secret
needsDatabase: true

env:
  NODE_ENV: "development"
  PORT: "4003"
