replicaCount: 2

image:
  repository: legiahoangthien/library-report-service
  tag: "prod-d0d1944083c2529becbd5b7a64ad3c932a37d801"

service:
  type: ClusterIP
  port: 4003

needsDatabase: true

env:
  NODE_ENV: "production"
  PORT: "4003"
