replicaCount: 2

image:
  repository: legiahoangthien/library-report-service
  tag: "prod-f93e0c7af38232764c81daf97a9a189ce2bd05ad"

service:
  type: ClusterIP
  port: 4003

needsDatabase: true

env:
  NODE_ENV: "production"
  PORT: "4003"
