replicaCount: 1

image:
  repository: lghthien/library-report-service
  tag: "dev-97df315ea31b5950ee394e10b7d3bc694d2294ef"

service:
  type: ClusterIP
  port: 4003

# Flag to determine if this service needs MongoDB credentials from Secret
needsDatabase: true

env:
  NODE_ENV: "development"
  PORT: "4003"
