replicaCount: 1

image:
  repository: lghthien/library-auth-service
  tag: "dev-initial"

service:
  type: ClusterIP
  port: 4001

# Flag to determine if this service needs MongoDB credentials from Secret
needsDatabase: true

env:
  NODE_ENV: "development"
  PORT: "4001"
