replicaCount: 1

image:
  repository: lghthien/library-auth-service
  tag: "dev-5fc177287a0db3b192ce8fb914df3a18a5a52124"

service:
  type: ClusterIP
  port: 4001

# Flag to determine if this service needs MongoDB credentials from Secret
needsDatabase: true

env:
  NODE_ENV: "development"
  PORT: "4001"
